tracer.property: "I AM THE DEFAULT"
spring.jpa.show-sql: "true"
spring.datasource.url:  "jdbc:mysql://localhost:3306/eagle_eye_local"
spring.datasource.username: "root"
spring.datasource.password: "rootpwd"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
#postgres://postgres:postgrespw@postgres:5432