server:
 port: 8888
spring:
 profiles:
  active: dev
 cloud:
  config:
   server:
    git:
     uri: https://github.com/nisarjava/config-repo.git
     searchPaths: configserver
     username: nisarjava@gmail.com
     password: Aaidah2010@d
     default-label: dev

#server:
# port: 8888
#spring:
# profiles:
#  active: native
# cloud:
#  config:
#   server:
#    native:
#     searchLocations: file:///Users/nisarab198/personal/PersonalOnIntelliJ/ConfigServer/src/main/resources/config/configserver