server:
 port: 8888
spring:
 profiles:
  active: dev
 cloud:
  config:
   server:
    git:
     uri: https://github.com/nisarjava/config-repo.git
    searchPaths: licensingservice
    username: native-cloud-apps
    password: 0ffended
    default-label: dev