server:
 port: 8888
spring:
 profiles:
  active: native
 cloud:
  config:
   server:
    native:
     searchLocations: file:///C://Users/nisarab198/personal/PersonalOnIntelliJ/ConfigServer/src/main/resources/config/licensingservice